// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOC.Shared.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace NOC.Web.Migrations
{
    [DbContext(typeof(NocDbContext))]
    [Migration("20260324032247_AddContactListsAndSegments")]
    partial class AddContactListsAndSegments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("text")
                        .HasColumnName("disabled_reason");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("PasswordUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("PasswordVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("password_version");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_email");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_events_actor_id_occurred_at");

                    b.HasIndex("EventType", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_events_event_type_occurred_at");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_events_entity_type_entity_id_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DelayMaxMs")
                        .HasColumnType("integer")
                        .HasColumnName("delay_max_ms");

                    b.Property<int>("DelayMinMs")
                        .HasColumnType("integer")
                        .HasColumnName("delay_min_ms");

                    b.Property<int>("DeliveredCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivered_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<Guid>("InboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_id");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<int>("MessagesPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("messages_per_minute");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("PausedReason")
                        .HasColumnType("text")
                        .HasColumnName("paused_reason");

                    b.Property<int>("ReadCount")
                        .HasColumnType("integer")
                        .HasColumnName("read_count");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<TimeOnly?>("SendWindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("send_window_end");

                    b.Property<TimeOnly?>("SendWindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("send_window_start");

                    b.Property<string>("SendWindowTz")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("send_window_tz");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer")
                        .HasColumnName("sent_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer")
                        .HasColumnName("total_recipients");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_campaigns_created_by");

                    b.HasIndex("InboxId")
                        .HasDatabaseName("ix_campaigns_inbox_id");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.CampaignRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_by");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("QUEUED")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_campaign_recipients");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_campaign_recipients_contact_id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_campaign_recipients_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_campaign_recipients_lease_expires_at")
                        .HasFilter("status = 'CLAIMED'");

                    b.HasIndex("CampaignId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_recipients_campaign_id_contact_id");

                    b.HasIndex("CampaignId", "Id")
                        .HasDatabaseName("ix_campaign_recipients_campaign_id_id")
                        .HasFilter("status = 'QUEUED'");

                    b.ToTable("campaign_recipients", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomAttrs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_attrs")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Locality")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("locality");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('spanish', coalesce(name, '') || ' ' || phone || ' ' || coalesce(email, '') || ' ' || coalesce(locality, ''))", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_phone");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_contacts_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_contact_lists");

                    b.ToTable("contact_lists", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactListMember", b =>
                {
                    b.Property<Guid>("ContactListId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_list_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ContactListId", "ContactId")
                        .HasName("pk_contact_list_members");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_contact_list_members_contact_id");

                    b.ToTable("contact_list_members", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactTag", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("TaggedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("tagged_by");

                    b.HasKey("ContactId", "Tag")
                        .HasName("pk_contact_tags");

                    b.HasIndex("Tag")
                        .HasDatabaseName("ix_contact_tags_tag");

                    b.HasIndex("TaggedBy")
                        .HasDatabaseName("ix_contact_tags_tagged_by");

                    b.ToTable("contact_tags", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset?>("AiEscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_escalated_at");

                    b.Property<bool>("AiHandled")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_handled");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("FirstResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_at");

                    b.Property<Guid>("InboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_id");

                    b.Property<DateTimeOffset?>("LastInboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inbound_at");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessageDirection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("last_message_direction");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_message_preview");

                    b.Property<DateTimeOffset?>("LastOutboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_outbound_at");

                    b.Property<short>("ReopenedCount")
                        .HasColumnType("smallint")
                        .HasColumnName("reopened_count");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snoozed_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("unread_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_conversations_closed_by");

                    b.HasIndex("ContactId", "InboxId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_contact_id_inbox_id")
                        .HasFilter("status NOT IN ('RESOLVED', 'ARCHIVED')");

                    b.HasIndex("ContactId", "Status")
                        .HasDatabaseName("ix_conversations_contact_id_status");

                    b.HasIndex("AssignedTo", "Status", "LastMessageAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_conversations_assigned_to_status_last_message_at")
                        .HasFilter("\"assigned_to\" IS NOT NULL");

                    b.HasIndex("InboxId", "Status", "LastMessageAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_conversations_inbox_id_status_last_message_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Inbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<string>("BanStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ban_status");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel_type");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config")
                        .HasDefaultValueSql("'{}'");

                    b.Property<short>("ConfigSchemaVer")
                        .HasColumnType("smallint")
                        .HasColumnName("config_schema_ver");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_access_token");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_refresh_token");

                    b.Property<string>("EvolutionInstanceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evolution_instance_name");

                    b.Property<DateTimeOffset?>("EvolutionLastHeartbeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evolution_last_heartbeat");

                    b.Property<string>("EvolutionSessionStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("evolution_session_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("ProxyOutboundId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxy_outbound_id");

                    b.Property<short>("SecretVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("secret_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_inboxes");

                    b.HasIndex("ProxyOutboundId")
                        .HasDatabaseName("ix_inboxes_proxy_outbound_id")
                        .HasFilter("proxy_outbound_id IS NOT NULL");

                    b.ToTable("inboxes", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.InboxAgent", b =>
                {
                    b.Property<Guid>("InboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.HasKey("InboxId", "AgentId")
                        .HasName("pk_inbox_agents");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_inbox_agents_agent_id");

                    b.ToTable("inbox_agents", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<DateTimeOffset?>("DeliveryUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_updated_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsPrivateNote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private_note");

                    b.Property<string>("MediaFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_filename");

                    b.Property<string>("MediaMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_mime_type");

                    b.Property<long?>("MediaSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("media_size_bytes");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("ProviderMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("provider_metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid?>("SentByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by_agent_id");

                    b.Property<bool>("SentByAi")
                        .HasColumnType("boolean")
                        .HasColumnName("sent_by_ai");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<string>("TemplateParams")
                        .HasColumnType("jsonb")
                        .HasColumnName("template_params");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_external_id")
                        .HasFilter("\"external_id\" IS NOT NULL");

                    b.HasIndex("SentByAgentId")
                        .HasDatabaseName("ix_messages_sent_by_agent_id");

                    b.HasIndex("DeliveryStatus", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_delivery_status_created_at")
                        .HasFilter("direction = 'OUTBOUND' AND delivery_status IN ('PENDING', 'QUEUED', 'RETRY_PENDING')");

                    b.HasIndex("ConversationId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_messages_conversation_id_created_at_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.MessageStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_message_status_events");

                    b.HasIndex("MessageId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_message_status_events_message_id_occurred_at");

                    b.ToTable("message_status_events", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<short>("EventVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("retry_count");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stream");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_events_created_at")
                        .HasFilter("published = false");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ProxyOutbound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int?>("LastTestLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("last_test_latency_ms");

                    b.Property<bool?>("LastTestOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_ok");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("protocol");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_proxy_outbounds");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_proxy_outbounds_created_by");

                    b.ToTable("proxy_outbounds", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules")
                        .HasDefaultValueSql("'[]'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_segments");

                    b.ToTable("segments", (string)null);
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .HasConstraintName("fk_audit_events_agents_actor_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "CreatedByAgent")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_campaigns_agents_created_by");

                    b.HasOne("NOC.Shared.Domain.Entities.Inbox", "Inbox")
                        .WithMany("Campaigns")
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_inboxes_inbox_id");

                    b.Navigation("CreatedByAgent");

                    b.Navigation("Inbox");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.CampaignRecipient", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Recipients")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_recipients_campaigns_campaign_id");

                    b.HasOne("NOC.Shared.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_recipients_contacts_contact_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactListMember", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Contact", "Contact")
                        .WithMany("ListMemberships")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_list_members_contacts_contact_id");

                    b.HasOne("NOC.Shared.Domain.Entities.ContactList", "ContactList")
                        .WithMany("Members")
                        .HasForeignKey("ContactListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_list_members_contact_lists_contact_list_id");

                    b.Navigation("Contact");

                    b.Navigation("ContactList");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactTag", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Contact", "Contact")
                        .WithMany("Tags")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_tags_contacts_contact_id");

                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "TaggedByAgent")
                        .WithMany()
                        .HasForeignKey("TaggedBy")
                        .HasConstraintName("fk_contact_tags_agents_tagged_by");

                    b.Navigation("Contact");

                    b.Navigation("TaggedByAgent");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("fk_conversations_agents_assigned_to");

                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "ClosedByAgent")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .HasConstraintName("fk_conversations_agents_closed_by");

                    b.HasOne("NOC.Shared.Domain.Entities.Contact", "Contact")
                        .WithMany("Conversations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_contacts_contact_id");

                    b.HasOne("NOC.Shared.Domain.Entities.Inbox", "Inbox")
                        .WithMany("Conversations")
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_inboxes_inbox_id");

                    b.Navigation("AssignedAgent");

                    b.Navigation("ClosedByAgent");

                    b.Navigation("Contact");

                    b.Navigation("Inbox");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Inbox", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.ProxyOutbound", "ProxyOutbound")
                        .WithMany("Inboxes")
                        .HasForeignKey("ProxyOutboundId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inboxes_proxy_outbounds_proxy_outbound_id");

                    b.Navigation("ProxyOutbound");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.InboxAgent", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "Agent")
                        .WithMany("InboxAgents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inbox_agents_agents_agent_id");

                    b.HasOne("NOC.Shared.Domain.Entities.Inbox", "Inbox")
                        .WithMany("InboxAgents")
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inbox_agents_inboxes_inbox_id");

                    b.Navigation("Agent");

                    b.Navigation("Inbox");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Message", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "SentByAgent")
                        .WithMany()
                        .HasForeignKey("SentByAgentId")
                        .HasConstraintName("fk_messages_agents_sent_by_agent_id");

                    b.Navigation("Conversation");

                    b.Navigation("SentByAgent");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.MessageStatusEvent", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Message", "Message")
                        .WithMany("StatusEvents")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_status_events_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ProxyOutbound", b =>
                {
                    b.HasOne("NOC.Shared.Domain.Entities.Agent", "CreatedByAgent")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_proxy_outbounds_agents_created_by");

                    b.Navigation("CreatedByAgent");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Agent", b =>
                {
                    b.Navigation("InboxAgents");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("ListMemberships");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ContactList", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Inbox", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Conversations");

                    b.Navigation("InboxAgents");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.Message", b =>
                {
                    b.Navigation("StatusEvents");
                });

            modelBuilder.Entity("NOC.Shared.Domain.Entities.ProxyOutbound", b =>
                {
                    b.Navigation("Inboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
